version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ADMINPASSWORD}
      ME_CONFIG_MONGODB_AUTH_DATABASE: ${DB_NAME}
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${DB_PASS}
    links:
      - mongo
    networks:
      - mongo-network

networks: 
  mongo-network:
    driver: bridge